config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  resources :users
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, uniqueness: true, presence:true,
    format: { with: /\S+@\S+\.\S+/, message: "not a valid email address" }
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to :users, notice: 'User was successfully registered.' 
    else
      render :new
    end
  end

  def index
    @users = User.all
  end

  private
    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :name, :date_of_birth)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstaTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <header class="navbar navbar-static-top navbar-inverse">
    <div class="container">
      <nav>
        <ul class="nav navbar-nav navbar-left">
          <li><%= link_to 'Home', new_user_path %></li>
          <li><%= link_to "List",  users_path %></li>
          <li><%= link_to 'nav3', '#' %></li>
          <li><%= link_to "nav4",  '#' %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to 'nav5', '#zxc' %></li>
        </ul>
      </nav>
    </div>
  </header>

  <div class='container'>
    <%= yield %>
  </div>
</body>
</html>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<h3>Listing Users</h3>
<br/>
<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Date of birth</th>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= user.date_of_birth %></td></tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div id="notice"><%= notice %></div>
<h3>User Registration</h3>
<br/>
<div class="row">
  <div class="col-md-6">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h4><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h4>
          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
        <% @user.errors.clear %>
      <% end %>
      <div id='client-errors' class='hidden'></div>   
      <div class="register-user">
        <div class="field">
          <%= f.label :email %>
          <%= f.email_field :email,  placeholder: 'Email'  %>
        </div>
        <div class="field">
          <%= f.label :password %>
          <%= f.password_field :password, placeholder: 'Password' %>
        </div>
        <div class="field">
          <%= f.label :confirm_password %>
          <%= f.password_field :password_confirmation, placeholder: 'Confirm password' %>
        </div>
        <br/>
        <div class="field">
          <%= f.label :name %>
          <%= f.text_field :name, placeholder: 'Name' %>
        </div>
        <div class="field">
          <%= f.label :date_of_birth %>
          <%= f.text_field :date_of_birth, placeholder: 'dd/mm/yyyy' %>
        </div>
        <div class="actions">
          <%= f.submit 'Register', id: 'user_register', class: 'btn btn-sm btn-primary pull-right' %>
        </div>
      </div>
    <% end %>
  </div>

  <div class='col-md-6 regular-text'>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
  </div>
</div>